name: admin_console
description: Dart starter for Appwrite function.
version: 1.0.0
publish_to: "none"

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  dart_appwrite: ^11.0.3
  dotenv: ^4.2.0
  faker: ^2.1.0
  totempole_services:
    path: "../"

dev_dependencies:
  lints: ^4.0.0
