name: totempole_services
description: Totempole services
version: 1.0.1
publish_to: "none"

environment:
  sdk: "^3.3.0"

dependencies:
  dart_appwrite: ^13.0.0
  faker: ^2.2.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.13 #usethis for now
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  lints: ^4.0.0
