name: totempole_services
description: Totempole services
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  dart_appwrite: ^11.0.1
  faker: ^2.1.0
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
      
dev_dependencies:
  build_runner: ^2.4.7
  freezed: ^2.4.5
  json_serializable: ^6.7.1
  lints: ^3.0.0
