name: totempole_services
description: Totempole services
version: 1.0.0
publish_to: 'none'

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies: 
  dart_appwrite: ^10.0.0
  faker: ^2.1.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.7.0
      
dev_dependencies:
  build_runner: ^2.3.2
  freezed: ^2.2.1
  json_serializable: ^6.5.4
  lints: ^3.0.0
